extends CanvasLayer

@export var Player : Node2D

@onready var MoneyCounter = $List/MoneyCounter

@onready var CurrentAddress = $List/CurrentAddress

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	MoneyCounter.text = "$" + str(Player.Money)
	
	if Player.ActiveContract:
		CurrentAddress.text = Player.ActiveContract.get_address()
	else:
		CurrentAddress.text = "No Active Contract"
